# This is a basic workflow to help you get started with Actions

name: Publish1

on:
  release:
    branches:
       - main
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '1.8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish package
        run: gradle publish
        env:
          GITTOKEN: ${{ secrets.GITTOKEN }}
          GITUSERNAME: ${{ secrets.GITUSERNAME }}
